# Generated by Django 3.2.6 on 2023-03-31 15:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('partner_type', models.CharField(choices=[('Entertainment', 'Entertainment'), ('BankRelated', 'BankRelated'), ('Shops', 'Shops'), ('Services', 'Services'), ('Food', 'Food'), ('Generic', 'Generic')], default='Generic', max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(max_length=400)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('timings', models.JSONField(blank=True, default={'24/7': True, 'everyday': True}, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('catalogue', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
