# Generated by Django 3.2.6 on 2023-03-31 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bankDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('card_type', models.CharField(default='basic', max_length=100)),
                ('card_perks', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankDetails.bankdetail')),
            ],
        ),
    ]
